timestamp = 2024-03-06T12:32:14Z
github = { repo = "intersectmbo/ouroboros-consensus", rev = "1172105b06748ff5af37dbee4402f6895e214d1a" }
subdir = 'ouroboros-consensus-cardano'

[[revisions]]
number = 1
timestamp = 2024-03-12T01:08:01Z

[[revisions]]
number = 2
timestamp = 2024-03-20T15:52:35Z
